### ISSUE TITLE
bootstrap-session-timeout

### ISSUE THREAD

**Issue by danishkhan86** [travishorn/jquery-sessionTimeout#13]
Hi, i am working on bootstrap-session-timeout in my asp.net project & my keepAliveUrl is not working when i clicked "stay connected" it do nothing, Please help me
here is the code
$.sessionTimeout({
title: "Your Session is About to Expire!",
message: "Your session is about to expire.",
logoutButton: "Logout",
keepAliveButton: "Stay Connected",
ajaxType: "POST",
ajaxData: "",
keepAliveUrl: absolute('', '/w/Login/KeepAlive.html'),
logoutUrl: absolute('', '/w/Login/logout.aspx?sid=1&url=<%= Request.Url.ToString()%>'),
warnAfter: 9e5,
redirAfter: 12e5,
keepAliveInterval: 5e3,
keepAlive: !0,
ignoreUserActivity: !1,
onStart: !1,
onWarn: !1,
onRedir: !1,
countdownMessage: !1,
countdownBar: !1,
countdownSmart: !1
)}

**Comment by travishorn** [comment]
You should try posting your issue to the [bootstrap-session-timeout](https://github.com/orangehill/bootstrap-session-timeout/issues) issues page. When you post there, don't forget to include any errors you're seeing in the console and/or any network activity you see when clicking the button.
