### ISSUE TITLE
Uncaught TypeError: $(...).modal is not a function

### ISSUE THREAD

**Issue by Amamatthew** [travishorn/jquery-sessionTimeout#15]
`bootstrap-session-timeout.js:163 Uncaught TypeError: $(...).modal is not a function
    at bootstrap-session-timeout.js:163`

**Comment by travishorn** [comment]
From the filename in the error, it looks like you are using a forked version of this library. More information might be found at https://github.com/orangehill/bootstrap-session-timeout or https://github.com/maxfierke/jquery-sessionTimeout-bootstrap
